import React, { createContext, useContext, useState } from 'react';

export type EventStatus = 'active' | 'draft';
export type EventCategory = 'Trips' | 'Games' | 'Sports' | 'Social' | 'Reading' | 'Music' | 'Culture';
export type PriceKey = 'free' | '5-10' | '10-20' | '20-50' | '50+';

export interface OrganizerEvent {
  id: string;
  organizerId?: string;
  title: string;
  venue: string;
  location: string;
  city: string;
  description: string;
  price: PriceKey;
  priceDisplay: string;
  category: EventCategory;
  photos: string[];
  emoji: string;
  date: string;
  time: string;
  spots: number;
  status: EventStatus;
}

export const PRICE_OPTIONS: { key: PriceKey; label: string }[] = [
  { key: 'free', label: 'Free' },
  { key: '5-10', label: '€5-10' },
  { key: '10-20', label: '€10-20' },
  { key: '20-50', label: '€20-50' },
  { key: '50+', label: '€50+' },
];

export const CATEGORIES: EventCategory[] = [
  'Trips', 'Games', 'Sports', 'Social', 'Reading', 'Music', 'Culture',
];

export const CATEGORY_EMOJI: Record<EventCategory, string> = {
  Trips: '🗺️',
  Games: '♟️',
  Sports: '🏓',
  Social: '🤝',
  Reading: '📚',
  Music: '🎶',
  Culture: '🎨',
};

const INITIAL_EVENTS: OrganizerEvent[] = [
  // ── Trips ─────────────────────────────────────
  {
    id: 'trip-bg-1',
    title: 'Weekend în Sofia',
    venue: 'Grup organizat',
    location: 'Centru, Cluj-Napoca',
    city: 'Cluj-Napoca',
    description: 'Excursie de weekend la Sofia cu microbuzul. Vizităm Catedrala Alexander Nevsky, Piața Sfântul Alexandru și centrul vechi. Cazare inclusă.',
    price: '20-50',
    priceDisplay: '€45',
    category: 'Trips',
    photos: ['https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?auto=format&fit=crop&w=800&q=80'],
    emoji: '🇧🇬',
    date: 'Vin 2 Mai - Dum 4 Mai',
    time: 'Plecare 6:00 AM',
    spots: 18,
    status: 'active',
  },
  {
    id: 'trip-ro-1',
    title: 'Zi la Transfăgărășan',
    venue: 'Grup organizat',
    location: 'Centru, Bucharest',
    city: 'Bucharest',
    description: 'Ieșire de o zi pe cel mai spectaculos drum din România. Lacul Bâlea, tunelul, priveliști de vis. Inclus: transport cu microbuzul.',
    price: '20-50',
    priceDisplay: '€30',
    category: 'Trips',
    photos: ['https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80'],
    emoji: '🏔️',
    date: 'Sâm 3 Mai',
    time: 'Plecare 5:30 AM',
    spots: 16,
    status: 'active',
  },
  {
    id: 'trip-ro-2',
    title: 'Weekend în Brașov',
    venue: 'Grup organizat',
    location: 'Centru, Cluj-Napoca',
    city: 'Cluj-Napoca',
    description: 'Două zile în Brașov: centrul vechi, Castelul Bran, Cetatea Râșnov. Cazare în hostel inclus. Perfect pentru cei noi în România.',
    price: '20-50',
    priceDisplay: '€55',
    category: 'Trips',
    photos: ['https://images.unsplash.com/photo-1555881400-74d7acaacd8b?auto=format&fit=crop&w=800&q=80'],
    emoji: '🏰',
    date: 'Sâm 3 - Dum 4 Mai',
    time: 'Plecare 7:00 AM',
    spots: 14,
    status: 'active',
  },
  {
    id: 'trip-ro-3',
    title: 'Zi la mare - Constanța & Mamaia',
    venue: 'Grup organizat',
    location: 'Centru, Bucharest',
    city: 'Bucharest',
    description: 'O zi la Marea Neagră. Plajă, promenadă, fructe de mare. Transport cu microbuzul dus-întors. Bine veniți toți.',
    price: '10-20',
    priceDisplay: '€18',
    category: 'Trips',
    photos: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80'],
    emoji: '🏖️',
    date: 'Dum 4 Mai',
    time: 'Plecare 6:30 AM',
    spots: 20,
    status: 'active',
  },
  {
    id: 'trip-ro-4',
    title: 'Sinaia - Castelul Peleș',
    venue: 'Grup organizat',
    location: 'Centru, Bucharest',
    city: 'Bucharest',
    description: 'Zi de excursie la Sinaia: Castelul Peleș, Castelul Pelișor și promenadă prin stațiune. Transport dus-întors inclus.',
    price: '10-20',
    priceDisplay: '€20',
    category: 'Trips',
    photos: ['https://images.unsplash.com/photo-1548185049-4be6d8bce9c0?auto=format&fit=crop&w=800&q=80'],
    emoji: '👑',
    date: 'Sâm 3 Mai',
    time: 'Plecare 8:00 AM',
    spots: 22,
    status: 'active',
  },
  {
    id: 'trip-ro-5',
    title: 'Salina Turda - zi de relaxare',
    venue: 'Grup organizat',
    location: 'Centru, Cluj-Napoca',
    city: 'Cluj-Napoca',
    description: 'Vizită la una dintre cele mai spectaculoase saline din lume. Lac subteran, parc de distracții și aer salin. Transport inclus.',
    price: '10-20',
    priceDisplay: '€15',
    category: 'Trips',
    photos: ['https://images.unsplash.com/photo-1504870712357-65ea720bc122?auto=format&fit=crop&w=800&q=80'],
    emoji: '⛏️',
    date: 'Dum 4 Mai',
    time: 'Plecare 9:00 AM',
    spots: 20,
    status: 'active',
  },
  // ── Cluj-Napoca ───────────────────────────────
  {
    id: 'ro-1',
    title: 'Șah pentru toți',
    venue: 'Cafeneaua Veche',
    location: 'Centru, Cluj-Napoca',
    city: 'Cluj-Napoca',
    description: 'Seară de șah pentru toate nivelele. Tablele sunt puse la dispoziție. Vino singur sau cu un prieten și facem echipe.',
    price: '5-10',
    priceDisplay: '€5',
    category: 'Games',
    photos: ['https://images.unsplash.com/photo-1529699211952-734e80c4d42b?auto=format&fit=crop&w=800&q=80'],
    emoji: '♟️',
    date: 'Joi 24 Apr',
    time: '7:00 PM',
    spots: 10,
    status: 'active',
  },
  {
    id: 'ro-10',
    title: 'Karaoke Social Cluj',
    venue: 'Baza Club',
    location: 'Mărăști, Cluj-Napoca',
    city: 'Cluj-Napoca',
    description: 'Karaoke relaxat, fără judecăți. Vino să cânți sau să râzi. Perfectă pentru cunoașterea oamenilor noi din Cluj.',
    price: '10-20',
    priceDisplay: '€10',
    category: 'Social',
    photos: ['https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=800&q=80'],
    emoji: '🎤',
    date: 'Sâm 26 Apr',
    time: '9:00 PM',
    spots: 50,
    status: 'active',
  },
  // ── Bucharest ─────────────────────────────────
  {
    id: 'ro-2',
    title: 'Alergare în parc',
    venue: 'Parcul Herăstrău',
    location: 'Herăstrău, Bucharest',
    city: 'Bucharest',
    description: 'Grupul nostru de alergare se întâlnește în fiecare sâmbătă dimineața. Ritmul este relaxat, bineveniți toți.',
    price: 'free',
    priceDisplay: 'Free',
    category: 'Sports',
    photos: ['https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&w=800&q=80'],
    emoji: '🏃',
    date: 'Sâm 26 Apr',
    time: '9:00 AM',
    spots: 25,
    status: 'active',
  },
  {
    id: 'ro-3',
    title: 'Club de lectură',
    venue: 'Librăria Cărturești',
    location: 'Centru Vechi, Bucharest',
    city: 'Bucharest',
    description: 'Luna aceasta citim „Moromeții". Aduce cartea și câteva gânduri. Discuție liberă, fără judecăți.',
    price: 'free',
    priceDisplay: 'Free',
    category: 'Reading',
    photos: ['https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&w=800&q=80'],
    emoji: '📚',
    date: 'Dum 27 Apr',
    time: '4:00 PM',
    spots: 18,
    status: 'active',
  },
  {
    id: 'ro-12',
    title: 'Seară de muzică folk',
    venue: 'Clubul Țăranului',
    location: 'Centru, Bucharest',
    city: 'Bucharest',
    description: 'Muzicieni amatori și profesioniști cântă folk românesc și internațional. Intrare liberă, atmosferă caldă.',
    price: 'free',
    priceDisplay: 'Free',
    category: 'Music',
    photos: ['https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&w=800&q=80'],
    emoji: '🎸',
    date: 'Vin 25 Apr',
    time: '8:30 PM',
    spots: 60,
    status: 'active',
  },
  // ── Timișoara ────────────────────────────────
  {
    id: 'ro-4',
    title: 'Seară Jazz & Vin',
    venue: 'Terasa Florilor',
    location: 'Fabric, Timișoara',
    city: 'Timișoara',
    description: 'Jazz live și vin local pe terasă. Intrare liberă, consumație minimă 20 lei. Atmosferă relaxată.',
    price: 'free',
    priceDisplay: 'Free',
    category: 'Music',
    photos: ['https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=800&q=80'],
    emoji: '🎷',
    date: 'Vin 25 Apr',
    time: '8:00 PM',
    spots: 40,
    status: 'active',
  },
  {
    id: 'ro-tm-2',
    title: 'Yoga în aer liber',
    venue: 'Parcul Rozelor',
    location: 'Fabric, Timișoara',
    city: 'Timișoara',
    description: 'Sesiune de yoga în parc, pentru toate nivelele. Adu-ți saltea și apă. Instructor certificat.',
    price: 'free',
    priceDisplay: 'Free',
    category: 'Sports',
    photos: ['https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=80'],
    emoji: '🧘',
    date: 'Dum 27 Apr',
    time: '9:00 AM',
    spots: 20,
    status: 'active',
  },
  {
    id: 'ro-tm-3',
    title: 'Speed Networking Timișoara',
    venue: 'Impact Hub',
    location: 'Centru, Timișoara',
    city: 'Timișoara',
    description: 'Întâlnire rapidă pentru profesioniști și freelanceri. 5 minute per conversație, conexiuni reale.',
    price: '5-10',
    priceDisplay: '€5',
    category: 'Social',
    photos: ['https://images.unsplash.com/photo-1497366216548-37526070297a?auto=format&fit=crop&w=800&q=80'],
    emoji: '🤝',
    date: 'Joi 24 Apr',
    time: '7:00 PM',
    spots: 30,
    status: 'active',
  },
  // ── Iași ─────────────────────────────────────
  {
    id: 'ro-5',
    title: 'Întâlnire Newcomers Iași',
    venue: 'Hub27',
    location: 'Păcurari, Iași',
    city: 'Iași',
    description: 'Dacă te-ai mutat recent în Iași, acesta e locul tău. Facem cunoștință, rupem gheața, poate ieșim după.',
    price: 'free',
    priceDisplay: 'Free',
    category: 'Social',
    photos: ['https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=800&q=80'],
    emoji: '🤝',
    date: 'Mie 23 Apr',
    time: '6:30 PM',
    spots: 30,
    status: 'active',
  },
  {
    id: 'ro-is-2',
    title: 'Atelier de pictură',
    venue: 'Studio 14',
    location: 'Tătărași, Iași',
    city: 'Iași',
    description: 'Atelier de pictură acrilică pentru începători și avansați. Materiale incluse în preț.',
    price: '10-20',
    priceDisplay: '€12',
    category: 'Culture',
    photos: ['https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=800&q=80'],
    emoji: '🎨',
    date: 'Sâm 26 Apr',
    time: '2:00 PM',
    spots: 14,
    status: 'active',
  },
  {
    id: 'ro-is-3',
    title: 'Seară de board games',
    venue: 'Dice & Friends',
    location: 'Copou, Iași',
    city: 'Iași',
    description: 'Jocuri de societate moderne: Catan, Ticket to Ride, Codenames și altele. Bine venit oricine.',
    price: '5-10',
    priceDisplay: '€5',
    category: 'Games',
    photos: ['https://images.unsplash.com/photo-1611996575749-79a3a250f948?auto=format&fit=crop&w=800&q=80'],
    emoji: '🎲',
    date: 'Vin 25 Apr',
    time: '6:00 PM',
    spots: 18,
    status: 'active',
  },
  // ── Brașov ───────────────────────────────────
  {
    id: 'ro-6',
    title: 'Ping Pong Open',
    venue: 'Sportarena Brașov',
    location: 'Schei, Brașov',
    city: 'Brașov',
    description: 'Turneu informal de tenis de masă. Toate nivelele binevenite. Echipamentul este furnizat.',
    price: '5-10',
    priceDisplay: '€8',
    category: 'Sports',
    photos: ['https://images.unsplash.com/photo-1534158914592-062992fbe900?auto=format&fit=crop&w=800&q=80'],
    emoji: '🏓',
    date: 'Sâm 26 Apr',
    time: '10:00 AM',
    spots: 16,
    status: 'active',
  },
  {
    id: 'ro-11',
    title: 'Hiking Poiana Brașov',
    venue: 'Telecabina Poiana',
    location: 'Poiana Brașov, Brașov',
    city: 'Brașov',
    description: 'Drumeție de weekend pe traseele din Poiana Brașov. Nivel mediu, durată ~3 ore. Aduce apă și bocanci buni.',
    price: 'free',
    priceDisplay: 'Free',
    category: 'Sports',
    photos: ['https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=80'],
    emoji: '🥾',
    date: 'Dum 27 Apr',
    time: '8:00 AM',
    spots: 15,
    status: 'active',
  },
  // ── Sibiu ─────────────────────────────────────
  {
    id: 'ro-7',
    title: 'Tur cultural Sibiu',
    venue: 'Piața Mare',
    location: 'Centru Istoric, Sibiu',
    city: 'Sibiu',
    description: 'Plimbare ghidată prin centrul istoric al Sibiului. Aflăm povești despre clădiri, legende locale și arhitectură.',
    price: '5-10',
    priceDisplay: '€6',
    category: 'Culture',
    photos: ['https://images.unsplash.com/photo-1490810194309-344cfd8edf52?auto=format&fit=crop&w=800&q=80'],
    emoji: '🏛️',
    date: 'Dum 27 Apr',
    time: '11:00 AM',
    spots: 20,
    status: 'active',
  },
  {
    id: 'ro-sb-2',
    title: 'Concurs de fotografie urbană',
    venue: 'Turnul Sfatului',
    location: 'Centru Istoric, Sibiu',
    city: 'Sibiu',
    description: 'Ieșim în oraș cu aparatele și telefonele. Tema: „Contraste". Câștigătorul e ales de grup.',
    price: 'free',
    priceDisplay: 'Free',
    category: 'Culture',
    photos: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80'],
    emoji: '📷',
    date: 'Sâm 26 Apr',
    time: '10:00 AM',
    spots: 25,
    status: 'active',
  },
  {
    id: 'ro-sb-3',
    title: 'Open Mic - muzică și poezie',
    venue: 'Café Wien',
    location: 'Centru, Sibiu',
    city: 'Sibiu',
    description: 'Urcă pe scenă sau stai în public. Orice instrument, orice voce. Atmosferă caldă garantată.',
    price: 'free',
    priceDisplay: 'Free',
    category: 'Music',
    photos: ['https://images.unsplash.com/photo-1478737270239-2f02b77fc618?auto=format&fit=crop&w=800&q=80'],
    emoji: '🎙️',
    date: 'Vin 25 Apr',
    time: '7:30 PM',
    spots: 50,
    status: 'active',
  },
  // ── Oradea ───────────────────────────────────
  {
    id: 'ro-8',
    title: 'Board Games Night',
    venue: 'Joyland Café',
    location: 'Ultracentral, Oradea',
    city: 'Oradea',
    description: 'Sute de jocuri de societate disponibile. Vino cu prietenii sau singur - facem echipe. Totul inclus în prețul cafelei.',
    price: '5-10',
    priceDisplay: '€5',
    category: 'Games',
    photos: ['https://images.unsplash.com/photo-1606503153255-59d8b8b82176?auto=format&fit=crop&w=800&q=80'],
    emoji: '🎲',
    date: 'Joi 24 Apr',
    time: '6:00 PM',
    spots: 24,
    status: 'active',
  },
  {
    id: 'ro-or-2',
    title: 'Alergare prin Cetate',
    venue: 'Cetatea Oradea',
    location: 'Cetate, Oradea',
    city: 'Oradea',
    description: 'Traseu de 5km prin zona istorică a orașului. Toate vitezele binevenite. Ne oprim pentru poze.',
    price: 'free',
    priceDisplay: 'Free',
    category: 'Sports',
    photos: ['https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?auto=format&fit=crop&w=800&q=80'],
    emoji: '🏃',
    date: 'Sâm 26 Apr',
    time: '8:30 AM',
    spots: 30,
    status: 'active',
  },
  {
    id: 'ro-or-3',
    title: 'Degustare de vinuri locale',
    venue: 'Cramele Bihor',
    location: 'Ultracentral, Oradea',
    city: 'Oradea',
    description: 'Degustare de vinuri din podgorii locale cu explicații despre soiuri și regiuni. Gustări incluse.',
    price: '20-50',
    priceDisplay: '€25',
    category: 'Social',
    photos: ['https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80'],
    emoji: '🍷',
    date: 'Dum 27 Apr',
    time: '6:00 PM',
    spots: 20,
    status: 'active',
  },
  // ── Craiova ──────────────────────────────────
  {
    id: 'ro-9',
    title: 'Concurs de poezie',
    venue: 'Casa de Cultură',
    location: 'Centru, Craiova',
    city: 'Craiova',
    description: 'Citim poezie proprie sau a altora. Nu e concurs cu premii - e un spațiu de exprimare. Toți sunt binevenitești.',
    price: 'free',
    priceDisplay: 'Free',
    category: 'Culture',
    photos: ['https://images.unsplash.com/photo-1474932430478-1aea786c0105?auto=format&fit=crop&w=800&q=80'],
    emoji: '🎨',
    date: 'Vin 25 Apr',
    time: '7:00 PM',
    spots: 35,
    status: 'active',
  },
  // ── Constanța ────────────────────────────────
  {
    id: 'ro-ct-1',
    title: 'Volleyball pe plajă',
    venue: 'Plaja Modern',
    location: 'Mamaia, Constanța',
    city: 'Constanța',
    description: 'Meci de volleyball pe nisip. Vino cu echipă sau formăm pe loc. Echipament furnizat.',
    price: 'free',
    priceDisplay: 'Free',
    category: 'Sports',
    photos: ['https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=800&q=80'],
    emoji: '🏐',
    date: 'Sâm 26 Apr',
    time: '10:00 AM',
    spots: 24,
    status: 'active',
  },
  {
    id: 'ro-ct-2',
    title: 'Seară de salsa și bachata',
    venue: 'Club Havana',
    location: 'Centru, Constanța',
    city: 'Constanța',
    description: 'Dans latin pentru toți: începători au o oră de inițiere gratuită înainte de petrecere.',
    price: '10-20',
    priceDisplay: '€10',
    category: 'Social',
    photos: ['https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&q=80'],
    emoji: '💃',
    date: 'Vin 25 Apr',
    time: '9:00 PM',
    spots: 60,
    status: 'active',
  },
  {
    id: 'ro-ct-3',
    title: 'Tur cu bicicleta pe faleză',
    venue: 'Faleza Casino',
    location: 'Faleza, Constanța',
    city: 'Constanța',
    description: 'Tur de 2 ore pe faleza Mării Negre. Biciclete disponibile pentru închiriere la fața locului.',
    price: '5-10',
    priceDisplay: '€8',
    category: 'Sports',
    photos: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80'],
    emoji: '🚴',
    date: 'Dum 27 Apr',
    time: '9:30 AM',
    spots: 15,
    status: 'active',
  },
  // ── Sofia ─────────────────────────────────────
  {
    id: 'bg-sf-1',
    title: 'Sofia Language Exchange',
    venue: 'The Библиотека Bar',
    location: 'Oborishte, Sofia',
    city: 'Sofia',
    description: 'Practice Bulgarian, English, Romanian and more. Relaxed format - pick a table by language and chat.',
    price: 'free',
    priceDisplay: 'Free',
    category: 'Social',
    photos: ['https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=800&q=80'],
    emoji: '🗣️',
    date: 'Joi 24 Apr',
    time: '7:00 PM',
    spots: 40,
    status: 'active',
  },
];

interface EventsContextType {
  events: OrganizerEvent[];
  addEvent: (event: Omit<OrganizerEvent, 'id'>) => string;
  updateEvent: (id: string, updates: Partial<OrganizerEvent>) => void;
  deleteEvent: (id: string) => void;
  getEvent: (id: string) => OrganizerEvent | undefined;
}

const EventsContext = createContext<EventsContextType | null>(null);

export function EventsProvider({ children }: { children: React.ReactNode }) {
  const [events, setEvents] = useState<OrganizerEvent[]>(INITIAL_EVENTS);

  const addEvent = (event: Omit<OrganizerEvent, 'id'>): string => {
    const id = Date.now().toString();
    setEvents((prev) => [{ ...event, id }, ...prev]);
    return id;
  };

  const updateEvent = (id: string, updates: Partial<OrganizerEvent>) => {
    setEvents((prev) => prev.map((e) => (e.id === id ? { ...e, ...updates } : e)));
  };

  const deleteEvent = (id: string) => {
    setEvents((prev) => prev.filter((e) => e.id !== id));
  };

  const getEvent = (id: string) => events.find((e) => e.id === id);

  return (
    <EventsContext.Provider value={{ events, addEvent, updateEvent, deleteEvent, getEvent }}>
      {children}
    </EventsContext.Provider>
  );
}

export function useEvents() {
  const ctx = useContext(EventsContext);
  if (!ctx) throw new Error('useEvents must be used within EventsProvider');
  return ctx;
}
