import type { SQLiteDatabase } from 'expo-sqlite';

export type EventStatus = 'active' | 'draft';
export type EventCategory = 'Trips' | 'Games' | 'Sports' | 'Social' | 'Reading' | 'Music' | 'Culture' | 'Online';
export type PriceKey = 'free' | '5-10' | '10-20' | '20-50' | '50+';

export interface OrganizerEvent {
  id: string;
  organizerId?: string;
  title: string;
  venue: string;
  location: string;
  city: string;
  description: string;
  price: PriceKey;
  priceDisplay: string;
  category: EventCategory;
  photos: string[];
  emoji: string;
  date: string;
  time: string;
  spots: number;
  status: EventStatus;
}

export type DbEventRow = Omit<OrganizerEvent, 'photos' | 'organizerId'> & {
  photos: string;
  organizerId: string | null;
};

export function rowToEvent(row: DbEventRow): OrganizerEvent {
  return {
    ...row,
    organizerId: row.organizerId ?? undefined,
    photos: JSON.parse(row.photos) as string[],
    price: row.price as PriceKey,
    category: row.category as EventCategory,
    status: row.status as EventStatus,
  };
}

export function eventToRow(e: OrganizerEvent): (string | number | null)[] {
  return [
    e.id,
    e.organizerId ?? null,
    e.title,
    e.venue,
    e.location,
    e.city,
    e.description,
    e.price,
    e.priceDisplay,
    e.category,
    JSON.stringify(e.photos),
    e.emoji,
    e.date,
    e.time,
    e.spots,
    e.status,
  ];
}

export const CREATE_TABLE = `
  CREATE TABLE IF NOT EXISTS events (
    id          TEXT    PRIMARY KEY,
    organizerId TEXT,
    title       TEXT    NOT NULL,
    venue       TEXT    NOT NULL,
    location    TEXT    NOT NULL,
    city        TEXT    NOT NULL,
    description TEXT    NOT NULL,
    price       TEXT    NOT NULL,
    priceDisplay TEXT   NOT NULL,
    category    TEXT    NOT NULL,
    photos      TEXT    NOT NULL,
    emoji       TEXT    NOT NULL,
    date        TEXT    NOT NULL,
    time        TEXT    NOT NULL,
    spots       INTEGER NOT NULL,
    status      TEXT    NOT NULL
  );
`;

export const INSERT_EVENT = `
  INSERT OR REPLACE INTO events
    (id, organizerId, title, venue, location, city, description, price, priceDisplay,
     category, photos, emoji, date, time, spots, status)
  VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
`;

export const SEED: OrganizerEvent[] = [
  {
    id: 'trip-bg-1',
    title: 'Weekend in Sofia',
    venue: 'Grup organizat',
    location: 'Centru, Cluj-Napoca',
    city: 'Cluj-Napoca',
    description: 'Excursie de weekend la Sofia cu microbuzul. Vizitam Catedrala Alexander Nevsky, Piata Sfantul Alexandru si centrul vechi. Cazare inclusa.',
    price: '20-50',
    priceDisplay: '€45',
    category: 'Trips',
    photos: ['https://images.unsplash.com/photo-1560969184-10fe8719e047?auto=format&fit=crop&w=800&q=80'],
    emoji: '🇧🇬',
    date: 'Vin 15 Mai - Dum 17 Mai',
    time: 'Plecare 6:00 AM',
    spots: 18,
    status: 'active',
  },
  {
    id: 'trip-ro-1',
    title: 'Zi la Transfagarasan',
    venue: 'Grup organizat',
    location: 'Centru, Bucharest',
    city: 'Bucharest',
    description: 'Iesire de o zi pe cel mai spectaculos drum din Romania. Lacul Balea, tunelul, privelisti de vis. Inclus: transport cu microbuzul.',
    price: '20-50',
    priceDisplay: '€30',
    category: 'Trips',
    photos: ['https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=80'],
    emoji: '🏔️',
    date: 'Sâm 10 Mai',
    time: 'Plecare 5:30 AM',
    spots: 16,
    status: 'active',
  },
  {
    id: 'trip-ro-2',
    title: 'Weekend in Brasov',
    venue: 'Grup organizat',
    location: 'Centru, Cluj-Napoca',
    city: 'Cluj-Napoca',
    description: 'Doua zile in Brasov: centrul vechi, Castelul Bran, Cetatea Rasnov. Cazare in hostel inclus. Perfect pentru cei noi in Romania.',
    price: '20-50',
    priceDisplay: '€55',
    category: 'Trips',
    photos: ['https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=800&q=80'],
    emoji: '🏰',
    date: 'Sâm 10 - Dum 11 Mai',
    time: 'Plecare 7:00 AM',
    spots: 14,
    status: 'active',
  },
  {
    id: 'trip-ro-3',
    title: 'Zi la mare - Constanta & Mamaia',
    venue: 'Grup organizat',
    location: 'Centru, Bucharest',
    city: 'Bucharest',
    description: 'O zi la Marea Neagra. Plaja, promenada, fructe de mare. Transport cu microbuzul dus-intors. Bine veniti toti.',
    price: '10-20',
    priceDisplay: '€18',
    category: 'Trips',
    photos: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80'],
    emoji: '🏖️',
    date: 'Dum 11 Mai',
    time: 'Plecare 6:30 AM',
    spots: 20,
    status: 'active',
  },
  {
    id: 'trip-ro-4',
    title: 'Sinaia - Castelul Peles',
    venue: 'Grup organizat',
    location: 'Centru, Bucharest',
    city: 'Bucharest',
    description: 'Zi de excursie la Sinaia: Castelul Peles, Castelul Pelisor si promenada prin statiune. Transport dus-intors inclus.',
    price: '10-20',
    priceDisplay: '€20',
    category: 'Trips',
    photos: ['https://images.unsplash.com/photo-1695045088081-1f37125905a2?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
    emoji: '👑',
    date: 'Sâm 10 Mai',
    time: 'Plecare 8:00 AM',
    spots: 22,
    status: 'active',
  },
  {
    id: 'trip-ro-5',
    title: 'Salina Turda - zi de relaxare',
    venue: 'Grup organizat',
    location: 'Centru, Cluj-Napoca',
    city: 'Cluj-Napoca',
    description: 'Vizita la una dintre cele mai spectaculoase saline din lume. Lac subteran, parc de distractii si aer salin. Transport inclus.',
    price: '10-20',
    priceDisplay: '€15',
    category: 'Trips',
    photos: ['https://images.unsplash.com/photo-1527856263669-12c3a0af2aa6?auto=format&fit=crop&w=800&q=80'],
    emoji: '⛏️',
    date: 'Dum 11 Mai',
    time: 'Plecare 9:00 AM',
    spots: 20,
    status: 'active',
  },
  {
    id: 'ro-1',
    title: 'Sah pentru toti',
    venue: 'Cafeneaua Veche',
    location: 'Centru, Cluj-Napoca',
    city: 'Cluj-Napoca',
    description: 'Seara de sah pentru toate nivelele. Tablele sunt puse la dispozitie. Vino singur sau cu un prieten si facem echipe.',
    price: '5-10',
    priceDisplay: '€5',
    category: 'Games',
    photos: ['https://images.unsplash.com/photo-1529699211952-734e80c4d42b?auto=format&fit=crop&w=800&q=80'],
    emoji: '♟️',
    date: 'Joi 14 Mai',
    time: '7:00 PM',
    spots: 10,
    status: 'active',
  },
  {
    id: 'ro-10',
    title: 'Karaoke Social Cluj',
    venue: 'Baza Club',
    location: 'Marasti, Cluj-Napoca',
    city: 'Cluj-Napoca',
    description: 'Karaoke relaxat, fara judecati. Vino sa canti sau sa razi. Perfecta pentru cunoasterea oamenilor noi din Cluj.',
    price: '10-20',
    priceDisplay: '€10',
    category: 'Social',
    photos: ['https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=800&q=80'],
    emoji: '🎤',
    date: 'Sâm 16 Mai',
    time: '9:00 PM',
    spots: 50,
    status: 'active',
  },
  {
    id: 'ro-2',
    title: 'Alergare in parc',
    venue: 'Parcul Herastrau',
    location: 'Herastrau, Bucharest',
    city: 'Bucharest',
    description: 'Grupul nostru de alergare se intalneste in fiecare sambata dimineata. Ritmul este relaxat, bienveniti toti.',
    price: 'free',
    priceDisplay: 'Free',
    category: 'Sports',
    photos: ['https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?auto=format&fit=crop&w=800&q=80'],
    emoji: '🏃',
    date: 'Sâm 9 Mai',
    time: '9:00 AM',
    spots: 25,
    status: 'active',
  },
  {
    id: 'ro-3',
    title: 'Club de lectura',
    venue: 'Libraria Carturesti',
    location: 'Centru Vechi, Bucharest',
    city: 'Bucharest',
    description: 'Luna aceasta citim "Morometii". Aduce cartea si cateva ganduri. Discutie libera, fara judecati.',
    price: 'free',
    priceDisplay: 'Free',
    category: 'Reading',
    photos: ['https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&w=800&q=80'],
    emoji: '📚',
    date: 'Dum 10 Mai',
    time: '4:00 PM',
    spots: 18,
    status: 'active',
  },
  {
    id: 'ro-12',
    title: 'Seara de muzica folk',
    venue: 'Clubul Taranului',
    location: 'Centru, Bucharest',
    city: 'Bucharest',
    description: 'Muzicieni amatori si profesionisti canta folk romanesc si international. Intrare libera, atmosfera calda.',
    price: 'free',
    priceDisplay: 'Free',
    category: 'Music',
    photos: ['https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&w=800&q=80'],
    emoji: '🎸',
    date: 'Vin 8 Mai',
    time: '8:30 PM',
    spots: 60,
    status: 'active',
  },
  {
    id: 'ro-4',
    title: 'Seara Jazz & Vin',
    venue: 'Terasa Florilor',
    location: 'Fabric, Timisoara',
    city: 'Timisoara',
    description: 'Jazz live si vin local pe terasa. Intrare libera, consumatie minima 20 lei. Atmosfera relaxata.',
    price: 'free',
    priceDisplay: 'Free',
    category: 'Music',
    photos: ['https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=800&q=80'],
    emoji: '🎷',
    date: 'Vin 8 Mai',
    time: '8:00 PM',
    spots: 40,
    status: 'active',
  },
  {
    id: 'ro-tm-2',
    title: 'Yoga in aer liber',
    venue: 'Parcul Rozelor',
    location: 'Fabric, Timisoara',
    city: 'Timisoara',
    description: 'Sesiune de yoga in parc, pentru toate nivelele. Adu-ti saltea si apa. Instructor certificat.',
    price: 'free',
    priceDisplay: 'Free',
    category: 'Sports',
    photos: ['https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=80'],
    emoji: '🧘',
    date: 'Dum 10 Mai',
    time: '9:00 AM',
    spots: 20,
    status: 'active',
  },
  {
    id: 'ro-tm-3',
    title: 'Speed Networking Timisoara',
    venue: 'Impact Hub',
    location: 'Centru, Timisoara',
    city: 'Timisoara',
    description: 'Intalnire rapida pentru profesionisti si freelanceri. 5 minute per conversatie, conexiuni reale.',
    price: '5-10',
    priceDisplay: '€5',
    category: 'Social',
    photos: ['https://images.unsplash.com/photo-1491438590914-bc09fcaaf77a?auto=format&fit=crop&w=800&q=80'],
    emoji: '🤝',
    date: 'Joi 14 Mai',
    time: '7:00 PM',
    spots: 30,
    status: 'active',
  },
  {
    id: 'ro-5',
    title: 'Intalnire Newcomers Iasi',
    venue: 'Hub27',
    location: 'Pacurari, Iasi',
    city: 'Iași',
    description: 'Daca te-ai mutat recent in Iasi, acesta e locul tau. Facem cunostinta, rupem gheata, poate iesim dupa.',
    price: 'free',
    priceDisplay: 'Free',
    category: 'Social',
    photos: ['https://images.unsplash.com/photo-1561283890-5d858c23b2ea?q=80&w=1076&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
    emoji: '🤝',
    date: 'Mie 13 Mai',
    time: '6:30 PM',
    spots: 30,
    status: 'active',
  },
  {
    id: 'ro-is-2',
    title: 'Atelier de pictura',
    venue: 'Studio 14',
    location: 'Tatarasi, Iasi',
    city: 'Iași',
    description: 'Atelier de pictura acrilica pentru incepatori si avansati. Materiale incluse in pret.',
    price: '10-20',
    priceDisplay: '€12',
    category: 'Culture',
    photos: ['https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=800&q=80'],
    emoji: '🎨',
    date: 'Sâm 9 Mai',
    time: '2:00 PM',
    spots: 14,
    status: 'active',
  },
  {
    id: 'ro-is-3',
    title: 'Seara de board games',
    venue: 'Dice & Friends',
    location: 'Copou, Iasi',
    city: 'Iași',
    description: 'Jocuri de societate moderne: Catan, Ticket to Ride, Codenames si altele. Bine venit oricine.',
    price: '5-10',
    priceDisplay: '€5',
    category: 'Games',
    photos: ['https://images.unsplash.com/photo-1611996575749-79a3a250f948?auto=format&fit=crop&w=800&q=80'],
    emoji: '🎲',
    date: 'Vin 8 Mai',
    time: '6:00 PM',
    spots: 18,
    status: 'active',
  },
  {
    id: 'ro-6',
    title: 'Ping Pong Open',
    venue: 'Sportarena Brasov',
    location: 'Schei, Brasov',
    city: 'Brașov',
    description: 'Turneu informal de tenis de masa. Toate nivelele binevenite. Echipamentul este furnizat.',
    price: '5-10',
    priceDisplay: '€8',
    category: 'Sports',
    photos: ['https://images.unsplash.com/photo-1534158914592-062992fbe900?auto=format&fit=crop&w=800&q=80'],
    emoji: '🏓',
    date: 'Sâm 9 Mai',
    time: '10:00 AM',
    spots: 16,
    status: 'active',
  },
  {
    id: 'ro-11',
    title: 'Hiking Poiana Brasov',
    venue: 'Telecabina Poiana',
    location: 'Poiana Brasov, Brasov',
    city: 'Brașov',
    description: 'Drumetie de weekend pe traseele din Poiana Brasov. Nivel mediu, durata ~3 ore. Aduce apa si bocanci buni.',
    price: 'free',
    priceDisplay: 'Free',
    category: 'Sports',
    photos: ['https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=800&q=80'],
    emoji: '🥾',
    date: 'Dum 10 Mai',
    time: '8:00 AM',
    spots: 15,
    status: 'active',
  },
  {
    id: 'ro-7',
    title: 'Tur cultural Sibiu',
    venue: 'Piata Mare',
    location: 'Centru Istoric, Sibiu',
    city: 'Sibiu',
    description: 'Plimbare ghidata prin centrul istoric al Sibiului. Aflam povesti despre cladiri, legende locale si arhitectura.',
    price: '5-10',
    priceDisplay: '€6',
    category: 'Culture',
    photos: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80'],
    emoji: '🏛️',
    date: 'Dum 10 Mai',
    time: '11:00 AM',
    spots: 20,
    status: 'active',
  },
  {
    id: 'ro-sb-2',
    title: 'Concurs de fotografie urbana',
    venue: 'Turnul Sfatului',
    location: 'Centru Istoric, Sibiu',
    city: 'Sibiu',
    description: 'Iesim in oras cu aparatele si telefonele. Tema: "Contraste". Castigatorul e ales de grup.',
    price: 'free',
    priceDisplay: 'Free',
    category: 'Culture',
    photos: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80'],
    emoji: '📷',
    date: 'Sâm 9 Mai',
    time: '10:00 AM',
    spots: 25,
    status: 'active',
  },
  {
    id: 'ro-sb-3',
    title: 'Open Mic - muzica si poezie',
    venue: 'Cafe Wien',
    location: 'Centru, Sibiu',
    city: 'Sibiu',
    description: 'Urca pe scena sau stai in public. Orice instrument, orice voce. Atmosfera calda garantata.',
    price: 'free',
    priceDisplay: 'Free',
    category: 'Music',
    photos: ['https://images.unsplash.com/photo-1478737270239-2f02b77fc618?auto=format&fit=crop&w=800&q=80'],
    emoji: '🎙️',
    date: 'Vin 8 Mai',
    time: '7:30 PM',
    spots: 50,
    status: 'active',
  },
  {
    id: 'ro-8',
    title: 'Board Games Night',
    venue: 'Joyland Cafe',
    location: 'Ultracentral, Oradea',
    city: 'Oradea',
    description: 'Sute de jocuri de societate disponibile. Vino cu prietenii sau singur - facem echipe. Totul inclus in pretul cafelei.',
    price: '5-10',
    priceDisplay: '€5',
    category: 'Games',
    photos: ['https://images.unsplash.com/photo-1606503153255-59d8b8b82176?auto=format&fit=crop&w=800&q=80'],
    emoji: '🎲',
    date: 'Joi 14 Mai',
    time: '6:00 PM',
    spots: 24,
    status: 'active',
  },
  {
    id: 'ro-or-2',
    title: 'Alergare prin Cetate',
    venue: 'Cetatea Oradea',
    location: 'Cetate, Oradea',
    city: 'Oradea',
    description: 'Traseu de 5km prin zona istorica a orasului. Toate vitezele binevenite. Ne oprim pentru poze.',
    price: 'free',
    priceDisplay: 'Free',
    category: 'Sports',
    photos: ['https://images.unsplash.com/photo-1571008887538-b36bb32f4571?auto=format&fit=crop&w=800&q=80'],
    emoji: '🏃',
    date: 'Sâm 9 Mai',
    time: '8:30 AM',
    spots: 30,
    status: 'active',
  },
  {
    id: 'ro-or-3',
    title: 'Degustare de vinuri locale',
    venue: 'Cramele Bihor',
    location: 'Ultracentral, Oradea',
    city: 'Oradea',
    description: 'Degustare de vinuri din podgorii locale cu explicatii despre soiuri si regiuni. Gustari incluse.',
    price: '20-50',
    priceDisplay: '€25',
    category: 'Social',
    photos: ['https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80'],
    emoji: '🍷',
    date: 'Dum 10 Mai',
    time: '6:00 PM',
    spots: 20,
    status: 'active',
  },
  {
    id: 'ro-9',
    title: 'Concurs de poezie',
    venue: 'Casa de Cultura',
    location: 'Centru, Craiova',
    city: 'Craiova',
    description: 'Citim poezie proprie sau a altora. Nu e concurs cu premii - e un spatiu de exprimare. Toti sunt bineveniti.',
    price: 'free',
    priceDisplay: 'Free',
    category: 'Culture',
    photos: ['https://images.unsplash.com/photo-1478641300939-0ec5188d3802?q=80&w=1172&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
    emoji: '🎨',
    date: 'Vin 8 Mai',
    time: '7:00 PM',
    spots: 35,
    status: 'active',
  },
  {
    id: 'ro-ct-1',
    title: 'Volleyball pe plaja',
    venue: 'Plaja Modern',
    location: 'Mamaia, Constanta',
    city: 'Constanța',
    description: 'Meci de volleyball pe nisip. Vino cu echipa sau formam pe loc. Echipament furnizat.',
    price: 'free',
    priceDisplay: 'Free',
    category: 'Sports',
    photos: ['https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=800&q=80'],
    emoji: '🏐',
    date: 'Sâm 9 Mai',
    time: '10:00 AM',
    spots: 24,
    status: 'active',
  },
  {
    id: 'ro-ct-2',
    title: 'Seara de salsa si bachata',
    venue: 'Club Havana',
    location: 'Centru, Constanta',
    city: 'Constanța',
    description: 'Dans latin pentru toti: incepatorii au o ora de initiere gratuita inainte de petrecere.',
    price: '10-20',
    priceDisplay: '€10',
    category: 'Social',
    photos: ['https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&q=80'],
    emoji: '💃',
    date: 'Vin 8 Mai',
    time: '9:00 PM',
    spots: 60,
    status: 'active',
  },
  {
    id: 'ro-ct-3',
    title: 'Tur cu bicicleta pe faleza',
    venue: 'Faleza Casino',
    location: 'Faleza, Constanta',
    city: 'Constanța',
    description: 'Tur de 2 ore pe faleza Marii Negre. Biciclete disponibile pentru inchiriere la fata locului.',
    price: '5-10',
    priceDisplay: '€8',
    category: 'Sports',
    photos: ['https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?auto=format&fit=crop&w=800&q=80'],
    emoji: '🚴',
    date: 'Dum 10 Mai',
    time: '9:30 AM',
    spots: 15,
    status: 'active',
  },
  {
    id: 'bg-sf-1',
    title: 'Sofia Language Exchange',
    venue: 'The Biblioteka Bar',
    location: 'Oborishte, Sofia',
    city: 'Sofia',
    description: 'Practice Bulgarian, English, Romanian and more. Relaxed format - pick a table by language and chat.',
    price: 'free',
    priceDisplay: 'Free',
    category: 'Social',
    photos: ['https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=800&q=80'],
    emoji: '🗣️',
    date: 'Joi 14 Mai',
    time: '7:00 PM',
    spots: 40,
    status: 'active',
  },
  // Online events — visible in every city
  {
    id: 'online-1',
    title: 'Trivia Night Online',
    venue: 'Discord',
    location: 'Online',
    city: 'Online',
    description: 'Seara de trivia cu intrebari din istorie, stiinta, cultura pop si sport. Echipe de pana la 4 jucatori. Linkul se trimite cu 10 minute inainte.',
    price: 'free',
    priceDisplay: 'Free',
    category: 'Online',
    photos: ['https://images.unsplash.com/photo-1606761568499-6d2451b23c66?auto=format&fit=crop&w=800&q=80'],
    emoji: '💻',
    date: 'Vin 9 Mai',
    time: '8:00 PM',
    spots: 40,
    status: 'active',
  },
  {
    id: 'online-2',
    title: 'Language Exchange Online',
    venue: 'Zoom',
    location: 'Online',
    city: 'Online',
    description: 'Sesiune saptamanala de schimb de limbi straine. Practica engleza, romana, franceza sau spaniola cu vorbitori nativi din toata lumea. Format relaxat, fara presiune.',
    price: 'free',
    priceDisplay: 'Free',
    category: 'Online',
    photos: ['https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&q=80'],
    emoji: '💻',
    date: 'Mie 14 Mai',
    time: '7:00 PM',
    spots: 30,
    status: 'active',
  },
  {
    id: 'online-3',
    title: 'Club de Lectura Online',
    venue: 'Google Meet',
    location: 'Online',
    city: 'Online',
    description: 'Discutam cartea lunii: "Sapiens" de Yuval Noah Harari. Intalnire de o ora, relaxata, deschisa oricui a citit macar o parte. Linkul se trimite dupa inscriere.',
    price: 'free',
    priceDisplay: 'Free',
    category: 'Online',
    photos: ['https://images.unsplash.com/photo-1513001900722-370f803f498d?auto=format&fit=crop&w=800&q=80'],
    emoji: '💻',
    date: 'Sam 17 Mai',
    time: '6:00 PM',
    spots: 25,
    status: 'active',
  },
];

const CREATE_SESSION_TABLE = `
  CREATE TABLE IF NOT EXISTS session (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    userId TEXT NOT NULL,
    userData TEXT NOT NULL,
    joinedEventIds TEXT NOT NULL DEFAULT '[]'
  );
`;

export async function initDatabase(db: SQLiteDatabase): Promise<void> {
  await db.execAsync('PRAGMA journal_mode = WAL;');
  await db.execAsync(CREATE_TABLE);
  await db.execAsync(CREATE_SESSION_TABLE);

  const row = await db.getFirstAsync<{ count: number }>(
    'SELECT COUNT(*) as count FROM events'
  );
  if ((row?.count ?? 0) === 0) {
    await db.withTransactionAsync(async () => {
      for (const event of SEED) {
        await db.runAsync(INSERT_EVENT, eventToRow(event));
      }
    });
  }
}
